# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-s7-50:part0:1.0 [current_project]
set_property ip_output_repo c:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.srcs/sources_1/new/bin6tobcd.vhd
  C:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.srcs/sources_1/new/hex2sseg.vhd
  C:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.srcs/sources_1/new/pwm.vhd
  C:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.srcs/sources_1/new/sseg_arty_2dig.vhd
  C:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.srcs/sources_1/new/sseg_control.vhd
  C:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.srcs/sources_1/new/pwm_vardisp3_arty.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.srcs/constrs_1/new/pwm.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Projects/WeatherStationPWM/WeatherStationPWM.srcs/constrs_1/new/pwm.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top pwm_vardisp3_arty -part xc7s50csga324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pwm_vardisp3_arty.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pwm_vardisp3_arty_utilization_synth.rpt -pb pwm_vardisp3_arty_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
